/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function selectFolder() {
    return invoke()<string>("select_folder")
}

export function getServedDir() {
    return invoke()<[string, number]>("get_served_dir")
}

export function getAvailableFiles() {
    return invoke()<string[]>("get_available_files")
}

export function saveCaptions(captions: ([string, string])[]) {
    return invoke()<null>("save_captions", { captions })
}

export function getTokenCounts(captions: string[]) {
    return invoke()<number[]>("get_token_counts", { captions })
}


